### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jourdain** [Kitware/py-web-vue#1]
- [ ] VTK/master (~10.0.0) available as wheel
  - [ ] X server
  - [ ] EGL
  - [ ] OSMesa
- [ ] WSLink - Py3 async/await
  - [ ] Better core framework (Tornedo/aiohttp/?)
  - [ ] Transport compression
  - [ ] Application compression
  - [ ] Async built-in
- [ ] ParaView (nightly/release)
  - [ ] VTK
  - [ ] WSLink
- [ ] More public application using it
   - [ ] Conceptual Modeler (GemPy++)
   - [ ] Visualizer -> ParaViewWeb
- [ ] PyWebVue features
  - [ ] State object handling
    - [ ] Files
    - [ ] TypedArray/Numpy with attachment usage
    - [ ] Compression per message
  - [ ] Dynamic registration of protocols
  - [ ] Example of dynamic client store extension and behavior 
    - [ ] Visualizer could the illustration of it
  - [ ] Deployment
    - [ ] Multi-clients built-in
      - [ ] Launcher multi-ports 
      - [ ] Launcher with dynamic proxying
    - [ ] Setup for docker / singularity deployment
      - [ ] Create a directory structure similar to was our generic PVW docker image expect 
      - [ ] Update our generic docker image to support such deployment
      - [ ] Singularity usage?
    - [ ] Integration into Plotly service offering

**Comment by patrickoleary** [comment]
Awesome! I can't wait.

**Comment by aaronchn** [comment]
What a great！

**Comment by jourdain** [comment]
@aaronchn you should checkout [trame](https://kitware.github.io/trame/) which is really a nice abstraction layer on top of py-web-vue. In reality py-web-vue will be break down into smaller pieces and renamed **trame-core**, **trame-widgets-vuetify**, **trame-widgets-***. Of course **trame** will only switch its internal import but it will keep the same API (so no breaking changes at the trame level).  This will allow us to better manage client/server code compatibility.

**Comment by aaronchn** [comment]
@jourdain 

As a novice with no web development experience, after reading the py-web-vue readme, I had the following possibly vague or incorrect perceptions：

SharedState is a core concept in trame or py-web-vue. This concept is a strong contender for the current client(data drive UI)<->ajax call<->restfull api(maybe like Flask) development pattern, and can even be called revolutionary.

The SharedState based web development pattern removes the clear boundary between client and server to some extent, which can be great, but there is an inertia in understanding the traditional web app pattern when trying or practicing it. This inertia may be a barrier to learning py-web-vue.

The SharedState based web development model somehow reduces the difficulty of web app development, or the skills required to get started.

SharedState based web development pattern, for the front and back-end close interaction scenario, such as VTK (I do not know this) may be very suitable, but can it basically or completely replace Django or Flask such web framework? I'm looking forward to seeing successful examples of this, which could be a boon to small or non-professional web developers.

Sorry, I haven't read the Trame documentation yet, so I'm not sure what the important differences are between the trame and py-web-vue projects, I'll try to learn more.

I don't mean to discredit the [vue.py](https://github.com/stefanhoelzl/vue.py) project, but as far as I understand it now, py-web-vue might be a more suitable choice for developing small webapp needs, so I hope I'm right.

Interesting, great, thank you!

**Comment by jourdain** [comment]
You can see the code difference between pywebvue and trame for a simple example

- vtk.js cone [PyWebVue](https://github.com/Kitware/py-web-vue/tree/master/examples/PlainPython/ClientOnlyVTK) / [trame](https://github.com/Kitware/trame/blob/master/examples/PlainPython/ClientOnlyVTK/app.py)
- VTK with local rendering [PyWebVue](https://github.com/Kitware/py-web-vue/tree/master/examples/VTK/SimpleCone/RemoteViewLocalRendering) / [trame](https://github.com/Kitware/trame/blob/master/examples/VTK/SimpleCone/LocalRendering.py)
